export class Product{
  // tslint:disable-next-line:max-line-length
  constructor(name: string = '', category: string = '', rating: number = 0, description: string = '', link : string = '', images: string[] = []) {
    this.id = Product.productsCounter++;
    this.images = images;
    this.name = name;
    this.rating = rating;
    this.description = description;
    this.link = link;
    this.category = category;
    this.likes = 0;
    // Category.newCategory(this.category);
  }

  static productsCounter = 1;
  // isCategory(categories: string[]) : boolean{
  //   for (let category of categories){
  //     if (this.category === category) return true;
  //   }
  //
  //   return false;
  // }

  static products = [
    new Product('One Piece: Stampede', 'Anime', 100, 'One Piece: Stampede is a 2019 Japanese animated fantasy action adventure film directed by Takashi Otsuka and produced by Toei Animation. It is the fourteenth feature film of the One Piece film series, based on the manga of the same name written and illustrated by Eiichiro Oda, and commemorates the anime\'s 20th anniversary. Oda was involved with the film as creative supervisor. It had its world premiere at the Osaka Station City Cinema in Osaka on August 1, 2019, and later released in Japan on August 9, 2019.', 'https://www.amazon.com/One-Piece-Stampede-Tetsuya-Endo/dp/B0859SS6P6/ref=sr_1_1?dchild=1&keywords=one+piece&qid=1614453802&s=movies-tv&sr=1-1', ['https://static.wikia.nocookie.net/onepiece/images/0/06/One_Piece_Stampede.png/revision/latest?cb=20190411110812&path-prefix=ru', 'https://external-preview.redd.it/zsQS6xEPzeu8kkS3o2yrz6UMWiuRI6t3IPrtpdG6ODo.jpg?auto=webp&s=8b02eb3eb151af429ace9addd2b7bc3acfbf58dc', 'https://i.pinimg.com/originals/3d/3d/6a/3d3d6ad1822f22135dafa11c0ae18e57.jpg']),
    new Product('My Hero Academia: Heroes Rising', 'Anime', 5, 'My Hero Academia (Japanese: 僕のヒーローアカデミア, Hepburn: Boku no Hīrō Akademia) is a Japanese superhero manga series written and illustrated by Kōhei Horikoshi. It has been serialized in Weekly Shōnen Jump since July 2014, with its chapters additionally collected into 29 tankōbon volumes as of January 2021. The story follows Izuku Midoriya, a boy born without superpowers (called Quirks) in a world where they have become commonplace, but who still dreams of becoming a superhero himself. He is scouted by All Might, Japan\'s greatest hero, who shares his Quirk with Midoriya after recognizing his potential, and later helps to enroll him in a prestigious high school for heroes in training.', 'https://www.amazon.com/My-Hero-Academia-Heroes-Rising/dp/B08L9RSMXV/ref=sr_1_1?dchild=1&qid=1614447239&refinements=p_n_theme_browse-bin%3A2650364011&rnid=2650362011&s=movies-tv&sr=1-1', ['https://musicart.xboxlive.com/7/24805100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080', 'https://m.media-amazon.com/images/M/MV5BNmQzYmE2MGEtZjk4YS00YmVjLWEwZWMtODRkMjc4MTM5N2I3XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg', 'https://d.newsweek.com/en/full/1569321/my-hero-academia-heroes-rising-poster.jpg']),
    new Product('RWBY: volume 1', 'Anime', 4.5, 'Volume 1 is the first season of RWBY. It premiered on July 18th, 2013 on the Rooster Teeth website, and ran until November 7th, 2013. It was preceded by the "color" trailers. It was followed by Volume 2.', 'https://www.amazon.com/RWBY-1-Barbara-Dunkelman/dp/B07BLS1BKX/ref=sr_1_8?dchild=1&qid=1614447239&refinements=p_n_theme_browse-bin%3A2650364011&rnid=2650362011&s=movies-tv&sr=1-8', ['https://musicart.xboxlive.com/7/03a01100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080', 'https://i.pinimg.com/originals/5b/49/22/5b4922bcab5e6f2df29f707dbf3bd957.jpg', 'https://img.discogs.com/-ik9huR9lGcRWkf7WMRA-E2MQIU=/fit-in/600x594/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13456091-1554560879-7849.jpeg.jpg']),
    new Product('Hunter x Hunter: The Last Mission', 'Anime', 4.6, 'Hunter × Hunter: The Last Mission (Japanese: 劇場版 HUNTER×HUNTER -The LAST MISSION-, Hepburn: Gekijō-ban Hantā Hantā Za Rasuto Misshon) is a 2013 Japanese animated feature film directed by Keiichiro Kawaguchi. The events of the film take place after "Greed Island arc", which is the fourth season finale and before "Chimera Ant arc", which is the fifth season premiere of Hunter x Hunter. Released on December 27, 2013, it is the second film based on the Hunter × Hunter manga series created by Yoshihiro Togashi. Viz Media released the film on home video in North America on March 12, 2019.', 'https://www.amazon.com/Hunter-x-Last-Mission/dp/B07TK4K2M6/ref=pd_rhf_se_s_pd_crcd_6?pd_rd_w=WDN8d&pf_rd_p=8019ba47-0a12-4976-b76b-5c932d60db6f&pf_rd_r=83CX232NP3TK6HF2YNYP&pd_rd_r=2b97f21f-d5dd-4d03-b2ac-3767f8ff8c91&pd_rd_wg=qTEyd&pd_rd_i=B07TK4K2M6&psc=1', ['https://m.media-amazon.com/images/M/MV5BNDkzMTBiM2YtM2ZkZi00NzM1LTg0ZWYtMTE1YmFiNzg5MjNmXkEyXkFqcGdeQXVyMjQ3NTQ4MjQ@._V1_.jpg', 'https://i.pinimg.com/originals/76/60/4d/76604df875c53c91e410e37a93bdccf3.jpg', 'https://de7i3bh7bgh0d.cloudfront.net/2019/01/10/21/28/43/0bffdcff-3b7f-4b1b-adc7-5a01584bb5a7/HxH_B5_1200x630.jpg', 'http://3.bp.blogspot.com/-XfWLGiArDcU/VChzdYQVayI/AAAAAAAACqw/P2_4KUPyYYM/s1600/Hunter-x-Hunter.jpg']),
    new Product('Dragon Ball Super: Broly', 'Anime', 4.7, 'Dragon Ball Super: Broly (Japanese: ドラゴンボール超スーパー ブロリー, Hepburn: Doragon Bōru Sūpā: Burorī) is a 2018 Japanese anime martial arts fantasy/adventure film, directed by Tatsuya Nagamine and written by Dragon Ball series creator Akira Toriyama. It is the twentieth Dragon Ball feature film overall, the third film produced with Toriyama\'s direct involvement, and the first to carry the Dragon Ball Super branding. Set after the events of the Universe Survival Saga depicted in Dragon Ball Super, the film follows series protagonists Goku and Vegeta as they encounter a powerful Saiyan named Broly. In the beginning, it tells the history of the Saiyans and the background story of these three Saiyans with different destinies connected to the turbulent period of their race, and later resulting in a massive fight between them.', 'https://www.amazon.com/Dragon-Ball-Super-Tatsuya-Nagamine/dp/B07PF3KRT5/ref=sr_1_4?dchild=1&qid=1614621569&refinements=p_n_theme_browse-bin%3A2650364011&rnid=2650362011&s=movies-tv&sr=1-4', ['https://m.media-amazon.com/images/M/MV5BMjhhMDU5Y2QtMzcyZS00ZGE1LTg3ZjMtMTYyOTM0OTFlYTRkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/81vIg0jh3EL.jpg', 'https://funart.pro/uploads/posts/2019-12/1577140185_12.png']),
    new Product('SAMSUNG XE310XBA-K02US', 'Computers & Laptops', 4.5, 'Model - XE310XBA-K02US, Release Date - October 2019, CPU - Intel N4000, CPU Cores  - 2, CPU Clock Rate  - 1100MHz, CPU Turbo Clock Rate - 2600MHz, RAM Size - 4GB, GPU - Intel UHD Graphics 600, SSD Capacity - 64GB, SSD Type - eMMC, Screen Size - 11.6", Resolution  - 1366 x 768, Panel Type - TN, Refresh Rate  - 60Hz, Dimensions - 202mm x 288mm x 17mm, Operating System - Google Chrome OS (64-bit), Weight - 1.18Kg', 'https://www.amazon.com/Samsung-Chromebook-Celeron-Processor-Gigabit/dp/B07XL4JHXR/ref=sr_1_3?dchild=1&qid=1614454420&s=computers-intl-ship&sr=1-3', ['https://images-na.ssl-images-amazon.com/images/I/8172kS3Ec-L._AC_SX450_.jpg', 'https://m.media-amazon.com/images/I/41Qyzwdqs3L._AC_.jpg', 'https://media.pangoly.com/img/2/d/0/f/2d0f49e7-de36-416d-9c92-2b03eaf7f72d.jpg', 'https://media.pangoly.com/img/1/4/5/1/1451b711-d256-4d24-b9eb-d8e35bb470e9.jpg']),
    new Product('Latitude 7420 2-in-1', 'Computers & Laptops', 4.5, 'Brand - Dell, Operating System - Windows 10 Pro, CPU Manufacturer - Intel, Screen Size - 14 Inches, Processor Count - 1', 'https://www.amazon.com/Latitude-7420-11-1145-16GB-256GB/dp/B08TY6GYV8/ref=sr_1_11?dchild=1&qid=1614622086&s=computers-intl-ship&sr=1-11', ['https://images-na.ssl-images-amazon.com/images/I/514o5N2AvjL._AC_.jpg', 'https://i1.wp.com/laptopmedia.com/wp-content/uploads/2021/02/la7420t_ctb_00030rf120_bk_5000x5000_gettyimages-1197597312_revised-scaled-e1613131645513.jpg?fit=1305%2C825&ssl=1', 'https://www.xda-developers.com/files/2021/01/Dell-Latitude-9420-2-in-1-product-image-1024x683.jpg']),
    new Product('Dell OptiPlex 7000 7450', 'Computers & Laptops', 1, 'Brand - Dell, CPU Model - Core i5, Computer Memory Size - 8 GB, Ram Memory Installed Size - 8 GB, Series - Optiplex', 'https://www.amazon.com/Dell-OptiPlex-7450-1920x1080-Quad-Core/dp/B07BFNHBSB/ref=sr_1_14?dchild=1&qid=1614623437&rnid=13896617011&s=computers-intl-ship&sr=1-14', ['https://images-na.ssl-images-amazon.com/images/I/71GLvXdy5wL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/719LYH6MBGL._AC_SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/616aBcl6yKL._AC_SL1500_.jpg']),
    new Product('5480 AIO', 'Computers & Laptops', 3, 'Brand - Dell, CPU Model - Core i5, Ram Memory Installed Size - 8 GB, Series - 02YC0, Graphics RAM Type - DDR4 SDRAM', 'https://www.amazon.com/5480-AIO-10500T-8GB-256GB/dp/B08MQV3J5V/ref=sr_1_23?dchild=1&qid=1614623437&rnid=13896617011&s=computers-intl-ship&sr=1-23', ['https://i.dell.com/is/image/DellContent//content/dam/global-asset-library/Products/Desktops/OptiPlex/24_5480_touch/op24_5480t_csy_00030lf95_bk_pd_km636.psd?qlt=95&fit=constrain,1&hei=500&wid=500&fmt=jpg&wid=570&hei=400', 'https://www.dateks.lv/images/pic/2400/2400/792/714.jpg', 'https://techcoza.b-cdn.net/wp-content/uploads/2020/08/Dell-OptiPlex-5480-aio-a.png']),
    new Product('HP Chromebook 14-inch HD Laptop', 'Computers & Laptops', 4.6, 'Brand - HP, Operating System - Chrome OS, CPU Manufacturer - Intel, Screen Size - 14 Inches, Computer Memory Size - 4 GB', 'https://www.amazon.com/HP-Chromebook-14-inch-Celeron-14a-na0010nr/dp/B08529TZMC/ref=sr_1_1?crid=NJIM1WJFH67Z&dchild=1&keywords=laptop&qid=1614703833&sprefix=lap%2Caps%2C335&sr=8-1', ['https://images-na.ssl-images-amazon.com/images/I/91shKLxoedL._AC_SL1500_.jpg', 'https://www.notebookcheck.net/fileadmin/Notebooks/HP/Chromebook_14_G1/4zu3_chromeb14.jpg', 'http://store.hp.com/app/assets/images/product/5VD66UA%23ABA/left_facing.png?_=1570281577617']),
    new Product('Raft Survival: Ocean Nomad - Simulator', 'Games', 3.7, 'Raft is a Survival Game developed by Redbeet Interactive and published by Axolot Games. By yourself or with friends, your mission is to survive an epic oceanic adventure across a perilous sea! Gather debris to survive, expand your raft and be wary of the dangers of the ocean! Trapped on a small raft with nothing but a hook made of old plastic, players awake on a vast, blue ocean totally alone and with no land in sight! With a dry throat and an empty stomach, survival will not be easy! Raft throws you and your friends into an epic adventure out on the big open sea, with the objective to stay alive, gather resources and build yourself a floating home worthy of survival. Resources are tough to come at sea: Players will have to make sure to catch whatever debris floats by using their trusty hook and when possible, scavenge the reefs beneath the waves. However, thirst and hunger is not the only danger in the ocean… watch out for the man-eating shark determined to end your voyage!', 'https://www.amazon.com/Raft-Survival-Ocean-Nomad-Simulator/dp/B08PL1MBST/ref=sr_1_4?dchild=1&keywords=game&qid=1614704106&rnid=2941120011&s=mobile-apps&sr=1-4', ['https://apkboat.com/logos/survival-on-raft-ocean-nomad-mod-free-craft-money.png', 'https://image.winudf.com/v2/image1/b2NlYW4ubm9tYWQuc3Vydml2YWwuc2ltdWxhdG9yX3NjcmVlbl83XzE1NjgwOTk2MTJfMDQ3/screen-7.jpg?fakeurl=1&type=.jpg', 'https://image.winudf.com/v2/image1/b2NlYW4ubm9tYWQuc3Vydml2YWwuc2ltdWxhdG9yX3NjcmVlbl85XzE1NjgwOTk2MTJfMDEy/screen-9.jpg?fakeurl=1&type=.jpg']),
    new Product('Hill Climb Racing 2', 'Games', 3.9, 'Hill Climb Racing 2 is the sequel to the most addictive and entertaining physics based driving game ever! And it’s free! Bill Newton is Back! After journeying where no driver has been before, Bill is ready to challenge the whole world in Hill Climb Racing multiplayer madness. Face new unique challenges in unique environments with many different cars. Defeat your opponents and collect big bonuses to tune your car and reach ever higher positions. With little respect to the laws of physics, Bill Newton will not rest until he has conquered the highest hills!!', 'https://www.amazon.com/Fingersoft-Hill-Climb-Racing-2/dp/B06Y1G9SS8/ref=sr_1_48?dchild=1&keywords=game&qid=1614704106&rnid=2941120011&s=mobile-apps&sr=1-48', ['https://images-na.ssl-images-amazon.com/images/I/510GXk4TAIL.jpg', 'https://static.wikia.nocookie.net/igromania/images/6/6e/Hill_Climb_Racing_2.jpg/revision/latest?cb=20170729084504&path-prefix=ru', 'https://play-lh.googleusercontent.com/UqTJPG3CXYtBACZcBi-9hKFFzlWt2OAgyN6QSx5CAfI4iyaeClOHK58CZ4Obm0tnCTVU']),
    new Product('Shark Sniping 2020', 'Games', 3.5, 'Squid Sniper is a weapon in Sharkbite. It costs 1,250 shark teeth. Like the Ray Gun, it takes a long time to grind up to 1,250, but it\'s worth the shark teeth considering its versatility. Although it is currently the highest damage weapon in the game, the weapon\'s slow firing speed limits its damage per second, which is not comparable to that of the Ray Gun Consequently, the squid sniper is generally not considered as good a weapon as the Ray Gun, however this weapon is very good for long range distances when the shark is far off to the other side of the map, it is although very slow when shot.', 'https://www.amazon.com/Tapinator-Shark-Sniping-2017/dp/B01L98BR08/ref=sr_1_104?dchild=1&keywords=game&qid=1614704815&rnid=2941120011&s=mobile-apps&sr=1-104', ['https://images-na.ssl-images-amazon.com/images/I/91AtDnBNA3L.png', 'https://images-na.ssl-images-amazon.com/images/I/71TYmOsINwL.jpg', 'https://images-na.ssl-images-amazon.com/images/I/71OQ4loruoL.jpg']),
    new Product('Geometry Dash Meltdown', 'Games', 3.9, 'Geometry Dash Meltdown is a free ad-supported expansion app of Geometry Dash developed and published by RobTop Games and released on December 19, 2015 for iOS and Android. It features 3 exclusive levels, with limited achievements, icons and collectibles. The ability to transfer certain unlockable data over to the full version through user accounts is also available.', 'https://www.amazon.com/RobTop-Games-Geometry-Dash-Meltdown/dp/B019IXVXCS/ref=sr_1_134?dchild=1&keywords=game&qid=1614704996&rnid=2941120011&s=mobile-apps&sr=1-134', ['https://images-na.ssl-images-amazon.com/images/I/91bzCDiryZL.png', 'https://static.wikia.nocookie.net/geometry-dash/images/b/b5/GeometryDashMeltdownPreview.png/revision/latest?cb=20151120201550', 'https://i.ytimg.com/vi/-872uCUHfDc/maxresdefault.jpg']),
    new Product('Sniper 3D Assassin: Shoot to Kill', 'Games', 3.5, 'The sniper is a character from a mobile app about being hired as a bounty hunter to take down criminals that cause issues in different regions of the world.', 'https://www.amazon.com/Sniper-3D-Assassin-Shoot-Shooting/dp/B01DJRQYTG/ref=sr_1_180?dchild=1&keywords=game&qid=1614704996&rnid=2941120011&s=mobile-apps&sr=1-180', ['https://images-na.ssl-images-amazon.com/images/I/816csVd6LJL.png', 'https://cdn.cloudflare.steamstatic.com/steam/apps/922320/capsule_616x353.jpg?t=1538576104', 'https://i1.sndcdn.com/artworks-000473474433-gyuh54-t500x500.jpg']),
    new Product('John Wick: Chapter 3 - Parabellum', 'Movies', 4.7, 'John Wick: Chapter 3 – Parabellum (also known as simply John Wick: Chapter 3) is a 2019 American neo-noir action thriller film starring Keanu Reeves as the eponymous character. It is the third installment in the John Wick film series, following John Wick (2014) and Chapter 2 (2017). The film is directed by Chad Stahelski and written by Derek Kolstad, Shay Hatten, Chris Collins, and Marc Abrams, based on a story by Kolstad. It also stars Halle Berry, Laurence Fishburne, Mark Dacascos, Asia Kate Dillon, Lance Reddick, Anjelica Huston, and Ian McShane. In the film, which picks up minutes after the end of the previous film, ex-hitman John Wick finds himself on the run from legions of assassins after a $14 million contract is put on his head due to his recent actions.', 'https://www.amazon.com/John-Wick-Chapter-3-Parabellum/dp/B07SV5HH14/ref=sr_1_3?crid=RCYNK7Z5FL7G&dchild=1&keywords=john+wick&qid=1614705351&sprefix=john+w%2Caps%2C345&sr=8-3', ['https://images-na.ssl-images-amazon.com/images/I/91wc7yc2R8L._SL1500_.jpg', 'https://www.vintagemovieposters.co.uk/wp-content/uploads/2019/06/IMG_9376.jpeg', 'https://miro.medium.com/max/4050/1*ylq6C6_wO0zGJgcfsQtYYw.jpeg']),
    new Product('Harry Potter: The Complete 8-Film Collection', 'Movies', 4.8, 'Harry Potter is a film series based on the eponymous novels by J. K. Rowling. The series is distributed by Warner Bros. and consists of eight fantasy films, beginning with Harry Potter and the Philosopher\'s Stone (2001) and culminating with Harry Potter and the Deathly Hallows – Part 2 (2011). A spin-off prequel series that will consist of five films started with Fantastic Beasts and Where to Find Them (2016), marking the beginning of the Wizarding World shared media franchise.', 'https://www.amazon.com/Harry-Potter-Complete-8-Film-Collection/dp/B005OCFGTO/ref=sr_1_2?dchild=1&keywords=movie&qid=1614705318&sr=8-2', ['https://images-na.ssl-images-amazon.com/images/I/91reTAYWeNL._SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/91wUGa1-TyL._SL1500_.jpg', 'https://specials-images.forbesimg.com/imageserve/5efa33eed4034b0007bf4b5c/960x0.jpg?fit=scale']),
    new Product('I see you', 'Movies', 4, 'I See You is a 2019 American crime horror film directed by Adam Randall, written by Devon Graye, produced by Matt Waldeck, and starring Helen Hunt, Jon Tenney, Judah Lewis, Owen Teague and Libe Barer.[3][4] It follows a suburban family beset by unexplainable events that may be linked to the recent disappearance of a young boy.', 'https://www.amazon.com/See-You-Greg-Alan-Williams/dp/B0829JQDTP/ref=sr_1_19?dchild=1&keywords=movie&qid=1614705744&sr=8-19', ['https://i0.wp.com/www.nightmarishconjurings.com/wp-content/uploads/2019/03/MV5BMmRhM2ZiYzUtYzljZi00YjMxLTk3NGUtMmIxZTRlMjc5ZjZlXkEyXkFqcGdeQXVyMTkzODQ2Mjk@._V1_.jpg?resize=432%2C640', 'https://musicart.xboxlive.com/7/cd505100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080', 'https://epidemz.net.co/uploads/posts/2020-05/1590686516_photo_2020-05-28_20-20-38.jpg']),
    new Product('Unhinged', 'Movies', 4.4, 'Unhinged is a 2020 American action thriller film[4][5][6] directed by Derrick Borte, from a screenplay by Carl Ellsworth. The film stars Russell Crowe, Caren Pistorius, Gabriel Bateman, Jimmi Simpson and Austin P. McKenzie. It tells the story of a young woman who is terrorized by a seemingly mentally ill stranger following a road rage incident.', 'https://www.amazon.com/Unhinged-Russell-Crowe/dp/B08LBNYTHY/ref=sr_1_17?dchild=1&keywords=movie&qid=1614705744&sr=8-17', ['https://images-na.ssl-images-amazon.com/images/I/911AEJ54h3L._AC_SL1500_.jpg', 'https://m.media-amazon.com/images/M/MV5BYjc1Mjg5NjItY2I2MS00NDk3LWI5NGYtNzZjNTNiZmMwZTA3XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg', 'https://m.media-amazon.com/images/M/MV5BZDdhMjkyOGEtY2M3OC00NGFjLTkyYjItMjgxMjg4NTMyOWM4XkEyXkFqcGdeQXVyODMzODk5MDQ@._V1_UY1200_CR109,0,630,1200_AL_.jpg']),
    new Product('Back to the Future Trilogy', 'Movies', 4.9, 'Back to the Future is an American science fiction adventure comedy film series written and directed by Robert Zemeckis, produced by Bob Gale and Neil Canton for Steven Spielberg\'s Amblin Entertainment, and distributed by Universal Pictures. The franchise follows the adventures of a high school student, Marty McFly (Michael J. Fox), an eccentric scientist, Doctor Emmett L. Brown (Christopher Lloyd), and Clara Clayton (Mary Steenburgen), in the third one, who is a schoolteacher, living and working in the schoolhouse outside Hill Valley, as they use a DeLorean time machine to time travel to different periods in the history of Hill Valley, California.', 'https://www.amazon.com/Back-Future-Trilogy-Blu-ray-Michael/dp/B011Q0FSC2/ref=sr_1_18?dchild=1&keywords=movie&qid=1614705744&sr=8-18', ['https://images-na.ssl-images-amazon.com/images/I/714f2FOU8sL._SL1500_.jpg', 'https://images-na.ssl-images-amazon.com/images/I/51-2MJCIr8L._SY445_.jpg', 'https://target.scene7.com/is/image/Target/GUEST_f5066494-16f0-4f66-8bb1-7b84530edc8c?wid=488&hei=488&fmt=pjpeg']),
  ];
  id: number;
  name: string;
  description: string;
  rating: number;
  images: string[];
  imageCnt = 0;
  link: string;
  likes: number;
  category: string;
  nextImage(x: number = 1): void{
    this.imageCnt += x;
    if (this.imageCnt >= this.images.length) { this.imageCnt = 0; }
    else if (this.imageCnt < 0) { this.imageCnt = this.images.length - 1; }
  }
  remove(): void{
    Product.products = Product.products.filter((product) => product.id !== this.id);
    // for (const product of Product.products){
    //   if (product.category === this.category) { return; }
    // }
    // Category.categories = Category.categories.filter((category) => category.name !== this.category);
  }
  like(): void{
    this.likes++;
  }
}
